import type { Types } from "mongoose";

export type WarehouseStatus =
  | "Active"
  | "Inactive"
  | "Under Maintenance"
  | "Full Capacity";

export interface InventorySummary {
  totalProducts: number;
  totalItemsInStock: number;
  totalStockValue: number;
  lowStockItemsCount: number;
  outOfStockItemsCount: number;
}

export interface InventoryItem {
  _id?: Types.ObjectId | string;
  product: Types.ObjectId | string;
  quantity: number;
}

export interface WarehouseAddress {
  building: string;
  town: string;
}

export type WarehouseListResponse = {
  warehouses: Warehouse[];
  totalWarehouses: number;
  currentPage: number;
  totalPages: number;
};

// Complete Warehouse Interface
export interface Warehouse {
  _id: Types.ObjectId | string;
  name: string;
  status: WarehouseStatus;
  warehouseCode: string; // Auto-generated by backend pre-save hook
  address: WarehouseAddress;
  inventorySummary?: InventorySummary;
  inventoryItems?: InventoryItem[];
  notes?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
}

// Payload interface for document creation (where auto-generated/default fields are optional)
export interface CreateWarehouseDTO {
  name: string;
  status?: WarehouseStatus;
  address: WarehouseAddress;
  inventorySummary?: Partial<InventorySummary>;
  inventoryItems?: Array<{ product: string; quantity: number }>;
  notes?: string;
}

export interface UpdateWarehouseDTO {
  name?: string;
  status?: WarehouseStatus;
  warehouseCode?: string; // Allowed if admin needs to manually override code
  address?: Partial<WarehouseAddress>; // Allows updating just town or building
  inventorySummary?: Partial<InventorySummary>;
  inventoryItems?: Array<{ product: string; quantity: number }>;
  notes?: string;
}
