import type { Types } from "mongoose";

export type ShopStatus = "Active" | "Inactive" | "Under Maintenance";
export type ShopType = "Retail Store" | "Showroom";

export interface InventorySummary {
  totalProducts: number;
  totalItemsInStock: number;
  totalStockValue: number;
  lowStockItemsCount: number;
}

export interface InventoryItem {
  _id?: Types.ObjectId | string;
  product: Types.ObjectId | string;
  quantity: number;
}

export interface ShopAddress {
  building: string;
  town: string;
}

export type ShopListResponse = {
  shops: Shop[];
  totalShops: number;
  currentPage: number;
  totalPages: number;
};

// Complete Shop Interface
export interface Shop {
  _id: Types.ObjectId | string;
  name: string;
  status: ShopStatus;
  shopCode: string; // Auto-generated by backend pre-save hook
  type: ShopType;
  address: ShopAddress;
  inventorySummary?: InventorySummary;
  inventoryItems?: InventoryItem[];
  notes?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
}

// Payload interface for document creation (where auto-generated/default fields are optional)
export interface CreateShopDTO {
  name: string;
  type: ShopType;
  address: ShopAddress;
  status?: ShopStatus;
  shopCode?: string; // Optional on input since backend handles auto-generation
  inventorySummary?: Partial<InventorySummary>;
  inventoryItems?: Array<{ product: string; quantity: number }>;
  notes?: string;
}

export interface UpdateShopDTO {
  name?: string;
  type?: ShopType;
  status?: ShopStatus;
  shopCode?: string; // Allowed if admin needs to manually override code
  address?: Partial<ShopAddress>; // Allows updating just town or building
  inventorySummary?: Partial<InventorySummary>;
  inventoryItems?: Array<{ product: string; quantity: number }>;
  notes?: string;
}
